[net]
git-fetch-with-cli = true

[alias]
sdk = "test --workspace --locked --test gateway actual_openai_ -- --ignored"
test-all = "test --workspace --locked -- --include-ignored"
e2e = "test --locked --test live -- --ignored"
