pub mod backend;
pub mod error;
pub mod files;
mod headers;
pub mod images;
mod lite_instructions;
mod memories;
pub mod native;
pub mod output;
pub mod realtime;
pub mod request;
mod search;
pub mod server;
pub mod settings;
pub mod standalone;
mod tools;
pub mod transfers;
pub mod transport;
pub mod websocket;

pub const CODEX_RELEASE: &str = "0.157.0";
pub const CODEX_REV: &str = "00c972ed5d6ff6499317fd41b7f23605b8e6850d";
