pub mod backend;
pub mod error;
pub mod files;
mod headers;
pub mod images;
mod lite_instructions;
mod memories;
pub mod native;
pub mod output;
pub mod realtime;
pub mod request;
mod search;
pub mod server;
pub mod settings;
pub mod standalone;
mod tools;
pub mod transfers;
pub mod transport;
pub mod websocket;

pub const CODEX_RELEASE: &str = "0.160.0";
pub const CODEX_REV: &str = "a956835d020762cb2b570053af06f643a11c0ecc";
